# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

type = "sink"
key = "elasticsearch"
enabled = true
version = 0
name = "Elasticsearch sink"
path = "../../target/debug/libiggy_connector_elasticsearch_sink"
verbose = false

[[streams]]
stream = "test_stream"
topics = ["test_topic"]
schema = "json"
batch_length = 100
poll_interval = "5ms"
consumer_group = "elasticsearch_sink_cg"

[plugin_config]
url = "http://localhost:9200"
index = "iggy_messages"
create_index_if_not_exists = true
batch_size = 100
timeout_seconds = 30
