# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

[versions]
# Flink
flink = "2.1.1"

# Pinot
pinot = "1.4.0"

# Jackson
jackson = "3.0.2"
jackson2 = "2.18.2"

# Apache Commons
commons-lang3 = "3.20.0"

# HTTP Client
httpclient5 = "5.5.1"

# Reactor
reactor-core = "3.8.0"
reactor-netty = "1.3.0"

# Logging
slf4j = "2.0.17"
logback = "1.5.21"

# Testing
junit = "6.0.1"
assertj = "3.27.6"
testcontainers = "2.0.2"

# Netty
netty = "4.2.7.Final"

# Spotbugs
spotbugs = "4.9.8"

# Config
typesafe-config = "1.4.5"

# Build plugins
spotless = "8.1.0"
shadow = "9.2.2"
checkstyle = "12.1.2"
jacoco = "0.8.14"

[libraries]
# Jackson
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
jackson2-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson2" }

# Pinot
pinot-spi = { module = "org.apache.pinot:pinot-spi", version.ref = "pinot" }

# Apache HTTP Client
httpclient5 = { module = "org.apache.httpcomponents.client5:httpclient5", version.ref = "httpclient5" }

# Apache Commons
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }

# Reactor
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor-core" }
reactor-netty-core = { module = "io.projectreactor.netty:reactor-netty-core", version.ref = "reactor-netty" }

# Logging
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Flink
flink-connector-base = { module = "org.apache.flink:flink-connector-base", version.ref = "flink" }
flink-streaming-java = { module = "org.apache.flink:flink-streaming-java", version.ref = "flink" }
flink-clients = { module = "org.apache.flink:flink-clients", version.ref = "flink" }
flink-test-utils = { module = "org.apache.flink:flink-test-utils", version.ref = "flink" }
flink-runtime-tests = { module = "org.apache.flink:flink-runtime", version.ref = "flink" }

# Testing
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

# Netty
netty-dns-macos = { module = "io.netty:netty-resolver-dns-native-macos", version.ref = "netty" }

# Spotbugs
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

# Config
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafe-config" }

[bundles]
testing = ["junit-jupiter", "junit-platform-launcher", "assertj-core"]

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
